const group_photos = [
    [
        "2020",
        "Names are listed below each image."
    ],
    [
        "2019",
        "From left to right, top to bottom:<br>Row 1: Manas Harbola, Kishore Kumar, Keenan Park, Abhinav Khandrika, Aditya Jain, Alexander Mayo, Hardik Bhardwaj, Sam Senzon, Jeffrey Zou, Alexander Wu, Jay Rana, Steven Wang, Albert Zou, Francisco del Campo, Daniel Xue, Erik Felvinczi, Jonathan Zhang, Andrew Wan, Locke Cai, Akshat Parthiban, Varun Chari, Ethan Soloway, Leonard Simon, Yuhao (Ben) Pan, Divraj Singh, Aaron Lozhkin, Ben Tomasic, Vatsin Suchak, Adamya Aggarwal<br>Row 2: William Kraft, Jeffrey Wang, Jeffrey Fang, Justin Lee, Peter Chen, Ansh Gadodia, Marcos Beraud-Valero, Saatvik Billa, Arjun Agrawal, Gil Shteyman, Kais Jessa, Roshan Ram, Ruthvik Mukkamala, Dhruv Pai, Aneesh Durai, Gautam Ramesh, Pramod Mitikiri, Ria Sharma, Mia Liang, Ananya Parashar, Ellen Zhang, Raymond Li, Pooja Patel, Justin Kim, Junyao Zheng, Dhruv Khurjekar<br>Row 3: Keaton Naff, Yash Samtani, Sidharth Srinivas, Kavin Saravanan, Siddarth Kunisetty, Anuraag Sarkar, Yifan Zhang, Youbin Park, Will (Suwei) Ma, Youjin Park, Anushka Gandhi, Shubha Vasisht, Ananya Balaji, Disha Kohli, Haley Dave, Ruchi Patel, Nikitha Subramaniam, Sreya Jonnalagadda, Margaret Zhu, Manav Singh, Swapneil Singh, Mihir Ram<br>Row 4: Rohit Jayas, Sri Akshara Kollu, Hasit Nanda, Darren Jia, Royce Koh, Akshat Satija, Krisha Mahajan, Priyal Garg, Anna Quiros, Andrew Lin, Allison Zhao, Riya Patel, Sreekruthi Dubagunta, Shreya Mogulothu, Ethan Cho, Irene Gil, Dheya Madhani, Jessica Wu, Meri Kavtelishvili, Marie Kim, Hriday Chheda, Sidharth Sankhe<br>Row 5: Milind Prabhu, Alex Zhang, Hyejun Shin, Sidharth Srivastava, Shubhum Agrawal, Serena Zeng, Eesha Sharma, Sabrina Yeung, Jenny Fan, Amber Wang, Tanya Das, Lisa Liu, Angelina Ye, Yuhua (Caroline) Chen, Seora Kim, Harshitha Thota, Meghana Kotcherlakota, Sneha Mukherjee, Anaya Mehta, Eva Zhu, Manya Zhu, Sophie Alcyone, Arsh Madhani, Tanushree Jain, Hengxuan Wang, Anushka Kansal, Ayyah Alhuraibi, Vihan Shah, Professor Rajiv Gandhi<br>Not Pictured: Aayush Gupta, Nina Chung, Tianyi Jia, Yufan Li, Sindhu Balamurugan, Aneesh Patnaik"
    ],
    [
        "2018",
        "From left to right, top to bottom:<br>Row 1: Zach Marks, Glenn Sun, Shreyas Srinivasan, Arihant Jain, Daniel Xue, Kishore Kumar, Shivam Agrawal, Yihe (Oscar) Liu, Surya Ananthu, Mateo Parrado, Jeffrey Cheng, Jack Hourigan, Bhargav Samineni, Shashank Rao, Manas Narula, Jamie Jacobs, John Carter, Adam Carpentieri, Yoganand Pathak<br>Row 2: Rohan Agrawal, Michael Zhang, Emily Hu, Elaine Wang, Aviel Resnick, Ahmed El-Morsy, Mahir Arora, Eunhae (Gracie) Chung, Kais Jessa, Ayush Vikram, Steven Liu, Harikesan Balachandran, Sarish Deotale, Jazlyn Pagan, Jason Li, Aditya Agashe<br>Row 3:  Yunha Park, Kiran Hiremath, Joanna Zhang, Emily Yang, Justin Kim, Sunny Chen, Albert Zou, Phillip Grabovsky, Shweta Kumar, Arsh Shah, Gokul Murugadoss, Ria Sharma, Ethan Soloway, Yonatan Wiese-Namir, Chengyuan Ma, Shivani Prusty, Parth Adhia, Franklin Hsu<br>Row 4:  Swapneil Singh, Jasmine Meelu, Cynthia Yao, Devrath Iyer, Lavina Mital, Sahar Sami, Elizabeth Berzin, Debdip (Rohan) Sengupta, Abhiram Vellore, Spencer Hua, Eric Yang, Jacob Alberts, Anushka Kansal, Srihitha Kariveda, Hannah Daniel, Ananya Parashar, Sanaya Gandhi, Tanushree Jain, Hung Nguyen, Dr. Pravesh Kothari<br>Row 5:  Saachi Khanna, Shubh Khanna, Maxwell Vale, Shruti Roy, Kate Kim, Ruhi Shah, Gil Shteyman, Ben Bigdelle, Krish Jetly, Helena Vasconcelos, Mahek Hemani, Simran Kaur, Paul Hamrick, Arunima Bhowmik, Ihyun Nam, Deepansha Singh, Josh Beigman, Aadityan Ganesh, Jakob Degen, Professor Rajiv Gandhi <br>Not Pictured: Ellie Shin, Jessica Yatvitskiy<br>T-shirt design credits (T-shirts not pictured): front: Glenn Sun, back: Daniel Xue"
    ],
    [
        "2017",
        "From left to right, top to bottom:<br>Row 1: Jakob Degen, David Carroll, Campbell Krulewski, Kevin Wu, Glenn Sun, Simrun Laroia, Jongwon Yeo, David Johnson, Rishi Sinha, Kishore Kumar, Pratham Rawat, Nalin Dwivedi, Dominykas Buracas, Akash Bajpai, William Berman, Vamsi Desu, Caleb Smith-Salzberg, Abhishek Patel, Rahul Ramaswamy, Jacob Petrisko, Jared Petrisko, Reagan Kan, Rohan Puthukudy, Thomas Shaw, Jasmine Meelu<br>Row 2: Joshua Ngotiaoco, Salil Desai, Rishab Bhatt, Daniel Cheng, Harleen Kaur, Kevin Hall, Abolee Raut, Rithika Raghav, Aanya Gupta, Zoe Pan, Louis Andre, Christopher Yu, Jimmy Li, Justin Lee, Nathan Kim, Josh Beigman, Luke Botta, Arihant Jain, Hung Nguyen, Harsh Parekh, Albert Wang<br>Row 3: Albert Zhang, Vinay Nair, Sebastian Jeon, Nishita Jain, Bharath Jaladi, Elaine Wang, Elizabeth Olshanetsky, Jessica Xu, Rhea Kapur, Sophia Ung, Eesha Sharma, Anu Vellore, Adrienne Wang, Kota Teasley, Elisabeth Gallou, Stephanie Luo, Julian Zhang, Ryan Xia, William Bednarz, Kaushik Vemparala, Zachary Marks, Mihir Shah, Peter Riera, Michael Chen, Karthik Sriram, Viswanath Nagarajan, Nalin Khanna, Ray Chen<br>Row 4: Aadityan Ganesh, Rajiv Gandhi, Paris Mielke, Ruchi Chheda, Larina Fu, Anusha Chheda, Catherine Phillips, Neha Nishikant, Thomas Quanci, Priyanka Chowdhury, Viki Mancoridis, Marina Mancoridis, Joanna Tasmin, Marie Kim, Robert Sargeant, Ojas Natu, Brandon Ho, Alex Zhang, Sunny Cheng, Thomas Kumpf, Sundarraman Madhusudan<br>Not Pictured: Jagdeep Bhatia, Ben Edelman, Sidhant Rastogi, Ben Hadad, Ananya Yammanuru<br>T-shirt design credits: front – Elizabeth Olshanetsky, back – Hung Nguyen"
    ],
    [
        "2016",
        "From left to right, bottom to top,<br>first row: Rajiv Gandhi, Tejas Gandhi, Saamia Khan, Aaira Bagga, Meghana Mehta, Anagha Prasad, Wanxing Lu, Jerry Qu, Joshua Park, Pierre Yan, Frederick Qiu, Robert Sargent, Ezra Edelman, Katrina Chen, Jasmine Romero, Roma Patel, Asha Agrawal, Anjali Agarwal, Ansh Nagda.<br>second row: Anushka Gandhi, Neha Nishikant, Rebecca Golm, Eden Fesseha, Vineeth Veeramachaneni, Neelay Trivedi, Darren Shachter, James Slattery, Jacqueline Lee, Connie Xu, Milo Hartsoe, Xinhe(Midori) Zhou, Clarissa Xu, Dominique Cho, Divya Unnam, Harsh Parekh.\nthird row: Devansh Chauhan, Rebecca Rovins, Arnav Mohan, Sammy Berger, Adam van Buren, Mitchell Yapaintng, Nalin Khanna, Thomas Quanci, James Kim, Nikhil Parchuri, Michaela Guo, Alice Lai, Charles Luo, Achyut Reddy, Mathew Weick, Devon Ulrich, Ricson Cheng (guest speaker), Tanvi Bajpai, Alina Kim, Mehaa Gupta.<br>fourth row: Pradhyun Tinnanur, Zarir Hamza, Kunal Adhia, Ethan Chen, Brandon Ho, Jagdeep Bhatia, Arin Mukherjee, Henry Claisse, Elizabeth Johnson, Elizabeth Qian, Pranay Musalimadugu, Mindy Li, Catherine Phillips, Shreyas Srinivasan, Warren Wang, Gianluca Gross, Matthew Benstock, Yuting (Jassmin) Deng, Sunny Cheng, Jim Tse.<br>Missing: Tanvi Wagle, Samuel Ugowe"
    ],
    [
        "2015",
        "From left to right, bottom to top (approximately), Sushant Patkar, Brian Mata, Shreyas Pai, Ben Yang, Pranav Iyer, Alok Tripathy, Alex Lin, Jon Chen, Ricson Cheng, Poojit Hegde ; Ben Edelman, Josh Reich, Olivia Weng, Daniel Lee, Mrigank Saksena, Robert Sargent, Tina Lu, Samantha Cheng, Jordan Bowman, Daniel Kim, Aditya Joshi ; Ezra Edelman, Michael Noronha, Timothy Dijamco, Minna Kim, Ishneet Sachar, Karen Shen, Hayun Chong, Karina Velez, Emily Liu, Viren Sawant ; Matthew Weick, Benjamin Firester, Grace Zhang, Carolina Zheng, Nidhi Shah, Olenka Jain, Jacob Edelman, Tejas Gandhi, Anushka Gandhi, Rajiv Gandhi, Nick Wee, Nikit Nainwal, Robert Liu, Martha Cryan, Timothy Tang, Alex Snyder ; Philip Vasseur, Mik Zlatin, Amnon Attali, Praveen Balaji, Steven Shan, Milo Hartsoe, Preston Choe, Alexandru Damian, Michael Yen, Alek John Kawczynski, Prathamesh Patil, Brian Goodchild, Jeet Mehta, Srisa Changolkar, Alexander Rittler, Matthew Haumann, Aditya Shastri, Avi Natan, Leon Yu Deng, Parshva Vakharia. Eitan Zlatin, Katon Luaces, and Andrew Mata also participated but are not pictured."
    ],
    [
        "2014",
        "From left to right, top to bottom (approximately), pictured students include Alok Tripathy, Vincent Taylor, Ben Yang, Justin Yi, Shreyas Pai, Daniel Jang, Rafael Haber, Pranav Iyer, Brendan DeMilt, Gala Taylor, Rohit Goyal, Parshva Vakharia, Amnon Attali, Ben Edelman, Colin Courchesne, Eleanor Avril, Eitan Zlatin, Michael Lim, Ricky Zhao, Alex Lin, Hrishikesh Khandeparker, Wanhui (Shiloh) Han, Joey Chalhoub, Johnathan Lin, Mohammed Nadeem, Julia Hou, Sophia Hu, Deanna Miceli, Tanvi Bajpai, Amulya Musipatla, Ricson Cheng, Mikhel Zlatin, Priscilla Liow, Mehaa Gupta, Nihar Sidhu, Harika Vedati, Tara Liu, Hayley Ye, Keaton Naff, Zixuan Zou, Jacob Edelman, Andrew Sikowitz, Alexandru Damian, Jeremy Ahn, Jessica Titensky, Selena Feng, Anushka Gandhi, Alison Shim, Olenka Jain, Katherine Scola, Hoon Oh, Tejas Gandhi, Christopher Hodsdon, Rajiv Gandhi, William Xiao, Johnathan Chen, Grant Wu, Kevin Chen, Nicholas Wee, Brian McGrath, Mark Lippincott, Andy Tran-Nguyen. Grace Zhang and Hyun Seoung Choi also participated but are not pictured."
    ],
    [
        "2013",
        "From left to right, top to bottom (approximately), pictured students include Matt Vasseur, Jeffrey Chen, Gala Taylor, Anand Nanduri, Chenduo Huang, Amnon Attali, Jacob van Buren, Pranav Iyer, Boxong Yin, Matt Troiani, Ben Edelman, Yuta Kakutani, Sunny Yin, Jerica Huang, Eitan Zlatin, Kooshul Jhaveri, Eric Liu, Minjae Kwon, Minna Kim, Siddarth Ghoshal, Alyssa Poletti, Jacob Edelman, Andrew Sikowitz, Changxu Lu, Yang Jiao, Anushka Gandhi, Tasha Parekh, Tejas Gandhi, Dr. Rajiv Gandhi, Nancy Zhang, Rebecca Tu, Kipsy Quevada, Jocelyn Huang, Hannah Chen, Richard Chu, Sudha Rao, Tim Stavetski, Hoon Oh, Katherine Scola, Grant Wu, Alex Lin, and Brian Brubach.  Carl Trimbach and Sumun Iyer also participated but are not pictured.  Photo taken by Frank Wojciechowski Photography."
    ],
    [
        "2012",
        "From left to right, top to bottom (approximately), pictured students include Casandra Monroe, Amit Chavan, Jacob Van Buren, Ansuman Das, Rob MacDavid, Pratyush Hiremath, Tim Hearn, Kshitijh Meelu, Michael Reininger, Max Pospischil, Varun Nambiar, John Christian Liang, Asra Mahmood, Oviya Arasu, Alex Lin,  Chris von Autenreid, Mike Hwang, Ben Edelman, Aaron Schankler, Vedant Hiroku, Amey Bhangale, Sumun Iyer, XiaoXu Zou, Julian Sit, Matt Cuevas, Ian Mertz, Dan Shen, Cheng Wang, David Jacobowitz, David Yang, Sudha Rao, Nicki Liang, Hoon Oh, Srujanee Pradhan, Joyce Li, and instructors Tejas Gandhi and Professor Rajiv Gandhi.  Michelle Kyin also participated but is not pictured."
    ],
    [
        "2011",
        "From left to right, pictured individuals are: David Jacobowitz, Dana Silver, Ruchi Chheda, Chris Jung, Akshay Subramaniam, Anusha Chheda, Arun Giridharan, Shagun Chheda, Sean Lowen, Ricky Zhao, Ajay Roopakalu, Ian Mertz, Henry Liu, Agastya Mondal, Daksh Sharma, Ian Persons, Michelle Lin, and Insia Zaidi.  Conrad Kramer and Thomas Greening also attended but are not in the picture."
    ]
]

export default group_photos;